# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Inno Barn. All rights reserved.

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "curamedon-backoffice.fullname" .) }}
type: Opaque
data:
  APP_SECRET: {{ .Values.app.secrets.appSecret | b64enc | quote }}
  DATABASE_ENCRYPTION_KEY: {{ .Values.app.secrets.databaseEncryptionKey | b64enc | quote }}
  INTERNAL_API_BASIC_AUTH: {{ .Values.app.secrets.internalApiBasicAuth | b64enc | quote }}
  RING_RING_API_KEY: {{ .Values.app.secrets.ringRingApiKey | b64enc | quote }}
  LUXEMBOURG_RING_RING_API_KEY: {{ .Values.app.secrets.luxembourgRingRingApiKey | b64enc | quote }}
  TELEGRAM_LOG_API_KEY: {{ .Values.app.secrets.telegramLogApiKey | b64enc | quote }}
  TELEGRAM_LOG_CHANNEL: {{ .Values.app.secrets.telegramLogChannel | b64enc | quote }}
  SENTRY_DSN: {{ .Values.app.secrets.sentryDsn | b64enc | quote }}
  GOOGLE_SERVICE_ACCOUNT_CREDS_CONTENT: {{ .Values.app.secrets.googleServiceAccountCredsContent | b64enc | quote }}
  GOOGLE_ANALYTICS_PROFILE_ID: {{ .Values.app.secrets.googleAnalyticsProfileId | b64enc | quote }}
