# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Inno Barn. All rights reserved.

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "curamedon-api.fullname" .) }}
type: Opaque
data:
  APP_SECRET: {{ .Values.app.secrets.appSecret | b64enc | quote }}
  DATABASE_ENCRYPTION_KEY: {{ .Values.app.secrets.databaseEncryptionKey | b64enc | quote }}
  MAILER_URL: {{ .Values.app.secrets.mailerUrl | b64enc | quote }}
  JWT_PASSPHRASE: {{ .Values.app.secrets.jwtPassphrase | b64enc | quote }}
  JWT_PUBLIC_KEY_CONTENT: {{ .Values.app.secrets.jwtPublicKeyContent | b64enc | quote }}
  JWT_PRIVATE_KEY_CONTENT: {{ .Values.app.secrets.jwtPrivateKeyContent | b64enc | quote }}
  MERCURE_JWT_KEY: {{ .Values.app.secrets.mercureJwtKey | b64enc | quote }}
  RING_RING_API_KEY: {{ .Values.app.secrets.ringRingApiKey | b64enc | quote }}
  LUXEMBOURG_RING_RING_API_KEY: {{ .Values.app.secrets.luxembourgRingRingApiKey | b64enc | quote }}
  GCORE_MEET_USER_PASSWORD: {{ .Values.app.secrets.gcoreMeetUserPassword | b64enc | quote }}
  BACKOFFICE_APP_USER_PASSWORD: {{ .Values.app.secrets.backooficeAppUserPassword | b64enc | quote }}
  CHAT_APP_USER_PASSWORD: {{ .Values.app.secrets.chatAppUserPassword | b64enc | quote }}
  UPLOADS_APP_USER_PASSWORD: {{ .Values.app.secrets.uploadsAppUserPassword | b64enc | quote }}
  TELEGRAM_LOG_API_KEY: {{ .Values.app.secrets.telegramLogApiKey | b64enc | quote }}
  TELEGRAM_LOG_CHANNEL: {{ .Values.app.secrets.telegramLogChannel | b64enc | quote }}
  OAUTH2_PRIVATE_KEY_PASSPHRASE: {{ .Values.app.secrets.oauth2PrivateKeyPassphrase | b64enc | quote }}
  OAUTH2_PUBLIC_KEY_CONTENT: {{ .Values.app.secrets.oauth2PublicKeyContent | b64enc | quote }}
  OAUTH2_PRIVATE_KEY_CONTENT: {{ .Values.app.secrets.oauth2PrivateKeyContent | b64enc | quote }}
  OAUTH2_ENCRYPTION_KEY: {{ .Values.app.secrets.oauth2EncryptionKey | b64enc | quote }}
  GOOGLE_API_KEY_DEFAULT: {{ .Values.app.secrets.googleApiKey | b64enc | quote }}
  GOOGLE_CLIENT_ID_DEFAULT: {{ .Values.app.secrets.googleApiClientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET_DEFAULT: {{ .Values.app.secrets.googleApiClientSecret | b64enc | quote }}
  MICROSOFT_CLIENT_ID_PROFESSIONAL: {{ .Values.app.secrets.microsoftClientIdProfessional | b64enc | quote }}
  MICROSOFT_CLIENT_SECRET_PROFESSIONAL: {{ .Values.app.secrets.microsoftClientSecretProfessional | b64enc | quote }}
  MICROSOFT_CLIENT_ID_NURSE: {{ .Values.app.secrets.microsoftClientIdNurse | b64enc | quote }}
  MICROSOFT_CLIENT_SECRET_NURSE: {{ .Values.app.secrets.microsoftClientSecretNurse | b64enc | quote }}
  SENTRY_DSN: {{ .Values.app.secrets.sentryDsn | b64enc | quote }}
  GOOGLE_MAPS_GEOCODE_API_KEY: {{ .Values.app.secrets.googleMapsGeocodeApiKey | b64enc | quote }}
  FIREBASE_API_KEY: {{ .Values.app.secrets.firebaseApiKey | b64enc | quote }}
