replicaCount: 1

image:
  repository: vsblty.azurecr.io/vsblty/vclight
  pullPolicy: IfNotPresent
  tag: "1.7.17"

display:
  displayName: unix:0
  EndpointId: 
  BaseCmsUrl: ""

imagePullSecrets: [name: regcred]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: true

resources: 
  limits:
    memory: "3072Mi"
  requests:
    memory: "3072Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
