# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Exium Inc.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.appName }}
    service: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.appName }}
    name: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
   - name: grpc-exe-health
     port: {{ .Values.service.port }}
     protocol: {{ .Values.service.protocol }}
   - name: http 
     port: 8080
