apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-14"
  name: address-secret-file
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
type: Opaque
data:
  address: {{ uuidv4 | b64enc }}
