apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    service.name: {{ .Values.analyticsEngine.serviceName }}
  name: {{ .Values.analyticsEngine.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.analyticsEngine.replicaCount }}
  selector:
    matchLabels:
      service.name: {{ .Values.analyticsEngine.serviceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "foghorn-edge.labels" . | nindent 8 }}
        service.name: {{ .Values.analyticsEngine.serviceName }}
        edge.foghorn.io/app-name: {{ .Values.analyticsEngine.serviceName }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: edge.foghorn.io/app-name
                operator: In
                values:
                - {{ .Values.messageBus.serviceName }}
            topologyKey: "kubernetes.io/hostname"    
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      containers:
      - env:
        - name: AE_COLLECTOR_LIMIT
          value: "{{ .Values.analyticsEngine.collectorLimit }}"
        - name: AE_MEMORY_WATERMARK_HIGH
          value: "{{ .Values.analyticsEngine.memoryWaterMarkHigh }}"
        - name: AE_MEMORY_WATERMARK_LOW
          value: "{{ .Values.analyticsEngine.memoryWaterMarkLow }}"
        - name: COMPONENT_NAME
          value: {{ .Values.analyticsEngine.componentName }}
        - name: MESSAGE_BUS_HOST
          value: {{ .Values.messageBus.componentName }}
        - name: WORKERS
          value: "{{ .Values.messageBus.workers }}"
        image: {{ .Values.image.repository }}/{{ .Values.image.releasesSubRepository }}{{ .Values.analyticsEngine.imageName }}{{ .Values.image.arch }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ .Values.analyticsEngine.componentName }}
        resources: {}
        volumeMounts:
        - mountPath: /fh_vol
          name: {{ .Values.volume.foghorn.name }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: {{ .Values.volume.foghorn.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeClaim.foghorn.name }}
status: {}
