apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-15"
  name: certs-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
type: Opaque
data:
  license-ca.crt: |
    {{ .Files.Get "files/certs/PROD-license-ca.crt" | b64enc }}
  ca-cert.pem: |
    {{ .Files.Get "files/certs/ca-cert.pem" | b64enc }}
  key.pem: |
    {{ .Files.Get "files/certs/key.pem" | b64enc }}
  cert.pem: |
    {{ .Files.Get "files/certs/cert.pem" | b64enc }}
