apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "16"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation,hook-failed"
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    edge.foghorn.io/created-for: cleanup
  name: "cleanup-folder-structure"
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        {{- include "foghorn-edge.labels" . | nindent 8 }}
        edge.foghorn.io/created-for: cleanup
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      serviceAccountName: cleanup-sa
      containers:
      - name: "cleanup-folder-structure"
        image: {{ .Values.busybox.image }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: [ 'sh' ]
        args: [ '-c', 'rm -rf /fh_vol/* /var/lib/influxdb/*' ]
        resources: {}
        volumeMounts:
        - name: {{ .Values.volume.foghorn.name }}
          mountPath: /fh_vol
        - mountPath: /var/lib/influxdb
          name: {{ .Values.volume.influx.name }}
      restartPolicy: Never
      volumes:
      - name: {{ .Values.volume.foghorn.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeClaim.foghorn.name }}
      - name: {{ .Values.volume.influx.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeClaim.influx.name }}
status: {}
