apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "14"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation,hook-failed"
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    edge.foghorn.io/created-for: cleanup
  name: "cleanup-em-apps"
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        {{- include "foghorn-edge.labels" . | nindent 8 }}
        edge.foghorn.io/created-for: cleanup
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      serviceAccountName: cleanup-sa
      initContainers:
      - name: init-cleanup-em-apps
        image: {{ .Values.busybox.image }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: [ 'sh' ]
        args: [ '-c', 'touch /fh_vol/fh/apps/make_kubectl_pass_when_no_apps.yaml' ]
        volumeMounts:
        - name: {{ .Values.volume.foghorn.name }}
          mountPath: /fh_vol
      containers:
      - name: "cleanup-em-apps"
        image: {{ .Values.kubectl.image }}
        command: [ 'kubectl' ]
        args: [ 'delete', '-f', '/fh_vol/fh/apps', '-R', '--ignore-not-found' ]
        resources: {}
        volumeMounts:
        - name: {{ .Values.volume.foghorn.name }}
          mountPath: /fh_vol
      restartPolicy: Never
      volumes:
      - name: {{ .Values.volume.foghorn.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeClaim.foghorn.name }}
status: {}
