apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    edge.foghorn.io/created-for: cleanup
  name: cleanup-sa
  namespace: {{ .Release.Namespace }}
