apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-13"
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
  name: em-container-list
  namespace: {{ .Release.Namespace }}
data:
  em-container-list.txt: |
{{ (tpl (.Files.Get "files/em-container-list.txt") .) | indent 4 }}
