apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    edge.foghorn.io/created-for: edgemanager
  name: {{ .Release.Namespace }}-em-sa
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: {{ .Values.image.pullSecret }}
