apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-8"
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    edge.foghorn.io/created-for: edgemanager
  name: {{ .Release.Namespace }}-em-sa-workloads-manager-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}-em-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Namespace }}-em-workloads-manager-role
  apiGroup: rbac.authorization.k8s.io
