apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-13"
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
  name: logrotate-properties
  namespace: {{ .Release.Namespace }}
data:
  fh-log-rotate: |
{{ .Files.Get "files/fh-log-rotate" | indent 4 }}
  logrotate: |
{{ .Files.Get "files/logrotate.sh" | indent 4 }}
  logrotate-daemon: |
{{ .Files.Get "files/logrotate_daemon.sh" | indent 4 }}
