apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    service.name: {{ .Values.mqttAgent.serviceName }}
  name: {{ .Values.mqttAgent.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "{{ .Values.mqttAgent.port }}"
    port: {{ .Values.mqttAgent.port }}
    targetPort: {{ .Values.mqttAgent.port }}
  selector:
    service.name: {{ .Values.mqttAgent.serviceName }}
