apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    service.name: {{ .Values.opcAgent.serviceName }}
  name: {{ .Values.opcAgent.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.opcAgent.replicaCount }}
  selector:
    matchLabels:
      service.name: {{ .Values.opcAgent.serviceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "foghorn-edge.labels" . | nindent 8 }}
        service.name: {{ .Values.opcAgent.serviceName }}
        edge.foghorn.io/app-name: {{ .Values.opcAgent.serviceName }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: edge.foghorn.io/app-name
                operator: In
                values:
                - {{ .Values.messageBus.serviceName }}
            topologyKey: "kubernetes.io/hostname"     
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      containers:
      - env:
        - name: COMPONENT_NAME
          value: {{ .Values.opcAgent.componentName }}
        - name: FOGHORN_BROKER_OPC_UA_OPTS
          value: -Demhost={{ .Values.edgemanager.componentName }} -Ddbushost={{ .Values.messageBus.componentName }} -Demport={{ .Values.edgemanager.port }} -Dlog4j.configuration=file:/fh_vol/fh/configs/logger/opc-agent-log4j.properties
            -Dlogback.configurationFile=file:/fh_vol/fh/configs/logger/opc-agent-logback.xml
        - name: JAVA_OPTS
          value: -XX:+ExitOnOutOfMemoryError
        image: {{ .Values.image.repository }}/{{ .Values.image.releasesSubRepository }}{{ .Values.opcAgent.imageName }}{{ .Values.image.arch }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ .Values.opcAgent.componentName }}
        resources: {}
        volumeMounts:
        - mountPath: /fh_vol
          name: {{ .Values.volume.foghorn.name }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: {{ .Values.volume.foghorn.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeClaim.foghorn.name }}
