apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "foghorn-edge.labels" . | nindent 4 }}
    service.name: {{ .Values.opcdaAgent.serviceName }}
  name: {{ .Values.opcdaAgent.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.opcdaAgent.replicaCount }}
  selector:
    matchLabels:
      service.name: {{ .Values.opcdaAgent.serviceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "foghorn-edge.labels" . | nindent 8 }}
        service.name: {{ .Values.opcdaAgent.serviceName }}
        edge.foghorn.io/app-name: {{ .Values.opcdaAgent.serviceName }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: edge.foghorn.io/app-name
                operator: In
                values:
                - {{ .Values.messageBus.serviceName }}
            topologyKey: "kubernetes.io/hostname"     
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      containers:
      - env:
        - name: COMPONENT_NAME
          value: {{ .Values.opcdaAgent.componentName }}
        image: {{ .Values.image.repository }}/{{ .Values.image.releasesSubRepository }}{{ .Values.opcdaAgent.imageName }}{{ .Values.image.arch }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ .Values.opcdaAgent.componentName }}
        resources: {}
        volumeMounts:
        - mountPath: /fh_vol
          name: {{ .Values.volume.foghorn.name }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: {{ .Values.volume.foghorn.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeClaim.foghorn.name }}
status: {}
