# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Blue Arcus Technologies, Inc

{{- if .Values.amf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "5gcore.fullname" . }}-amf-cm-1
  labels:
    app: {{ template "5gcore.name" . }}-amf
    {{- include "5gcore.labels" . | nindent 4 }}
data:
  amfcfg.yaml: |-
{{ .Files.Get "scripts/amf/amfcfg.yaml" | indent 4 }}
{{- end }}
