# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Frinx s. r. o.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-elasticsearch-master-0
spec:
  storageClassName: "elasticsearch-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: elasticsearch-master-elasticsearch-master-0-pv

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "elasticsearch-storage"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-elasticsearch-master-0-pv
spec:
  storageClassName: "elasticsearch-storage"
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/elasticsearch/elasticsearch-master-elasticsearch-master-0-pv
    type: DirectoryOrCreate
