# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- hosts: localhost
  roles:
    - role: machine_setup/localhost
    - role: docker
    - role: docker_registry/localhost
    - role: common/build
      when: build_eis_base_images | default(True)
    - role: camera_stream/build
    - role: etcd/build
    - role: video_ingestion/build
    - role: video_analytics/build
    - role: visualizer/build

- hosts: controller_group
  roles:
    - role: machine_setup/k8s_master
    - role: common/deploy
    - role: camera_stream/deploy
      when: camera_stream_pod | default(True)
    - role: etcd/deploy
    - role: video_analytics/deploy
    - role: visualizer/deploy
    - role: video_ingestion/deploy
