# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Inno Barn. All rights reserved.

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "curamedon-oauth.fullname" .) }}
type: Opaque
data:
  APP_SECRET: {{ .Values.app.secrets.appSecret | b64enc | quote }}
  DATABASE_ENCRYPTION_KEY: {{ .Values.app.secrets.databaseEncryptionKey | b64enc | quote }}
  RING_RING_API_KEY: {{ .Values.app.secrets.ringRingApiKey | b64enc | quote }}
  LUXEMBOURG_RING_RING_API_KEY: {{ .Values.app.secrets.luxembourgRingRingApiKey | b64enc | quote }}
  TELEGRAM_LOG_API_KEY: {{ .Values.app.secrets.telegramLogApiKey | b64enc | quote }}
  TELEGRAM_LOG_CHANNEL: {{ .Values.app.secrets.telegramLogChannel | b64enc | quote }}
  SENTRY_DSN: {{ .Values.app.secrets.sentryDsn | b64enc | quote }}
  OAUTH2_PRIVATE_KEY_PASSPHRASE: {{ .Values.app.secrets.oauth2PrivateKeyPassphrase | b64enc | quote }}
  OAUTH2_PUBLIC_KEY_CONTENT: {{ .Values.app.secrets.oauth2PublicKeyContent | b64enc | quote }}
  OAUTH2_PRIVATE_KEY_CONTENT: {{ .Values.app.secrets.oauth2PrivateKeyContent | b64enc | quote }}
  OAUTH2_ENCRYPTION_KEY: {{ .Values.app.secrets.oauth2EncryptionKey | b64enc | quote }}
