# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Altran Technology
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "v2xstack.serviceAccountName" . }}
  labels:
    {{- include "v2xstack.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
