# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Albora Technologies Ltd.
{{- if .Values.image }}
{{- if .Values.image.registry }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "product.fullname" . -}}-docker-credentials
data:
  .dockerconfigjson: {{ template "container.credentials" . }}
{{- end }}
{{- end }}

