# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Albora Technologies Ltd.

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "product.fullname" . -}}-secrets
  labels:
    io.albora.product: {{ include "product.fullname" . }}
data:
  ntripCaster.password: {{ .Values.casterPassword | b64enc }}
  refstationmanagerpostgresql.password: {{ .Values.assetmanagerpostgresql.postgresqlPassword | b64enc }}
  assetmanagerpostgresql.password: {{ .Values.refstationmanagerpostgresql.postgresqlPassword | b64enc }}
