# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Nabstract.io

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: mysql
