# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Kibernetika, Inc. All rights reserved.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audience-db
spec:
  selector:
    matchLabels:
      app: audience
      component: audience-db
  template:
    metadata:
      labels:
        app: audience
        component: audience-db
    spec:
      containers:
        - name:  audience-db
          image: postgres:9.6.2
          env:
            - name: POSTGRES_USER
              value: {{ .Values.api.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.api.db.password }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: psql
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data/pgdata
              subPath: audience-db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: audience-db
