# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Kibernetika, Inc. All rights reserved.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audience-images
spec:
  {{- if .Values.persistence.db.storageClass }}
  storageClassName: {{ .Values.persistence.images.storageClass | quote }}
  {{- end }}
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.persistence.images.size }}
