# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - name: https
    targetPort: ctk-loadkey
    port: {{ .Values.ctk_loadkey.main.port }}
    nodePort: {{ .Values.ctk_loadkey.node_port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
