# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Albora Technologies Ltd.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "product.fullname" . -}}-rtk-collector
  labels:
    io.albora.product: {{ include "product.fullname" . }}
    io.albora.service: rtk-collector
spec:
  selector:
    io.albora.product: {{ include "product.fullname" . }}
    io.albora.service: rtk-collector
  type: ClusterIP
  ports:
    - name: "api"
      protocol: TCP
      port: {{ int .Values.apiPort }}
      targetPort: {{ int .Values.apiPort }}
