# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvino-prod-app

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openvino-prod-app-csr-requester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csr-requester
subjects:
  - kind: ServiceAccount
    name: openvino-prod-app
    namespace: default

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openvino-prod-app-csr-config
data:
  certrequest.json: |
    {
        "CSR": {
            "Name": "openvino-prod-app",
            "Subject": {
                "CommonName": "openvino:producer",
                "Organization": ["Intel Corporation"]
            },
            "DNSSANs": [],
            "IPSANs": [],
            "KeyUsages": [
                "digital signature", "key encipherment", "client auth"
            ]
        },
        "Signer": "openness.org/certsigner",
        "WaitTimeout": "5m"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvino-prod-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvino-prod-app
  template:
    metadata:
      labels:
        app: openvino-prod-app
    spec:
      serviceAccountName: openvino-prod-app
      initContainers:
        - name: alpine
          image: alpine:3.12.0
          command: ["/bin/sh"]
          args: ["-c", "cp /root/ca-certrequester/cert.pem /root/certs/root.pem"]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "0.1"
            limits:
              cpu: "0.1"
              memory: "128Mi"
          volumeMounts:
            - name: ca-certrequester
              mountPath: /root/ca-certrequester
            - name: certs
              mountPath: /root/certs
        - name: certrequester
          image: certrequester:1.0
          imagePullPolicy: Never
          args: ["--cfg", "/home/certrequester/config/certrequest.json"]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "0.1"
            limits:
              cpu: "0.1"
              memory: "128Mi"
          volumeMounts:
            - name: config
              mountPath: /home/certrequester/config/
            - name: certs
              mountPath: /home/certrequester/certs/
      containers:
        - name: openvino-prod-app
          image: openvino-prod-app:1.0
          imagePullPolicy: Never
          ports:
          - containerPort: 443
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: certs
              mountPath: /root/certs/
      volumes:
        - name: tmp
          hostPath:
            path: /tmp
            type: Directory
        - name: config
          configMap:
            name: openvino-prod-app-csr-config
        - name: ca-certrequester
          secret:
            secretName: ca-certrequester
        - name: certs
          emptyDir: {}
