# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Herta Security

apiVersion: v1
kind: Service
metadata:
  name: {{ include "hc-openness.fullname" . }}
  labels:
    {{- include "hc-openness.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hc-openness.selectorLabels" . | nindent 4 }}
