# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Inno Barn. All rights reserved.

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-run-migrations" (include "curamedon-api.fullname" .) }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-run-migrations" (include "curamedon-api.name" .) }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: run-migrations
          image: "{{ .Values.php.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["php", "-d", "memory_limit=200M", "bin/console", "d:m:m", "-n"]
          env:
            - name: MESSENGER_ASYNC_TRANSPORT_DSN
              value: {{ printf "redis://%s/messages" (include "curamedon-api.redisHost" .)}}
            - name: ELASTIC_SEARCH_HOST
              value: {{ include "curamedon-api.elasticsearchHost" . }}
            - name: DATABASE_URL
              value: {{ printf "mysql://%s:%s@%s/%s" .Values.app.secrets.dbUser .Values.app.secrets.dbPassword (include "curamedon-api.mysqlHost" .) .Values.app.secrets.dbName }}
          envFrom:
            - secretRef:
                name: {{ printf "%s-secrets" (include "curamedon-api.fullname" .) }}
            - configMapRef:
                name: {{ printf "%s-configs" (include "curamedon-api.fullname" .) }}
      restartPolicy: Never
