# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Exium Inc.

# Default values for upf-sess.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

appName: n3iwf
name: n3iwf-eap5g
version: v1

image:
  repository: gcr.io/ec2nf-256816/n3iwf-eap5g
  tag: v2.0.0-933dbf2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5057
  name: eap5g
  protocol: TCP

  udpport: 6000
  udpname: eap5gUdp
  udpprotocol: UDP

gateway:
  enabled: true

resources:
  requests:
    memory: "64Mi"
    cpu: "150m"
  limits:
    memory: "1024Mi"
    cpu: "200m"

env:
  redisMaster: "redis-master.exopsagent:6379"
  redisSlave: "redis-slave.exopsagent:6379"
  jaegerServer: "jaeger-agent.exopsagent:6831"
  logLevel: "trace"
  enableTracer: true
  enableMetrics: true
  metricsSuffix: "/metrics"
  metricsPort : "8080"
  enableNats: true
  enableCfgMgr: true
  natsServer: "nats://nats-client.nats:4222"
  fluentServer: "fluentd"
  usePreConfKn3iwf: false
  eap5gServerIp: "0.0.0.0"
  eap5gPort: "6000"
  eap5gServerModuleName: "server"
  exedgeName: ""
  n3iwfName: ""

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: 
      paths: []
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
