# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Astri Corporation
#
apiVersion: v1
kind: Service
metadata:
  name: upf-agent
spec:
  type: NodePort
  selector:
    app: upf-agent
  ports:
  - protocol: TCP
    port: 9191
    targetPort: 9191
    nodePort: 30000
