# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: Delete eis pod
  shell:  source {{ eis_sources_dir }}/build/.env; kubectl delete -f eis-k8s-deploy.yml
  args:
    chdir: "{{ eis_sources_dir }}/build/k8s"
  changed_when: true
  ignore_errors: yes

- name: delete pcb image
  command : "docker rmi {{ docker_registry_address }}{{ item }}:{{ eis_image_tag }}"
  with_items:
    - ia_video_ingestion
    - ia_video_analytics
    - ia_visualizer
    - ia_web_visualizer
  changed_when: true
  ignore_errors: yes

- name: delete safety image
  command : "docker rmi {{ docker_registry_address }}{{ item }}:{{ eis_image_tag }}"
  with_items:
    - python_safety_gear_analytics
    - python_safety_gear_ingestion
  when: demo_type == 'safety'
  changed_when: true
  ignore_errors: yes
