# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Astri Corporation

# Default values for upf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
  
replicaCount: 1 
nodeSelector: 
  kubernetes.io/hostname: node01

vpp:
  image:
    repository: astri.org/5g/upf
    tag: v22.03-rc0 
    pullPolicy: IfNotPresent

  n3:
    sriovNetworkName: sriov-n2n3 
    ipAddress: 192.168.28.176
    mask: 24
       
  n4:
    podIPAddr: true
    vf:
      sriovNetworkName: sriov-n4
      ipAddress: 192.168.23.177
      mask: 24

  n6:
    sriovNetworkName: sriov-n6 
    ipAddress: 192.168.24.197
    mask: 24
    gw: 192.168.24.1
  
  edgeAppNetworks: "10.96.0.10/32"
  ueNetworks: "172.20.0.0/16, 172.21.0.0/16" 
  vethPeerHostAddress: "172.30.30.1/24"
  vethPeerVppAddress: "172.30.30.30/24"
  
  n6NatEnable: true
  dnsRedirectEnable: false
  dnsServerIP: "10.96.0.10"
  
  licenseSecret: license-node01  

  resources:
    requests:
      memory: 6144Mi
      cpu: "4"
      intel.com/intel_sriov_UPF_OUT: "1"
      intel.com/intel_sriov_UPF_IN: "1"
    limits:
      memory: 6144Mi
      cpu: "4"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_UPF_OUT: "1"
      intel.com/intel_sriov_UPF_IN : "1"

  initresources:
    requests:
      memory: 256Mi
      cpu: 256m
    limits:
      memory: 256Mi
      cpu: 256m

vppagent:
  image:
    repository: astri.org/5g/upf-agent
    tag: v22.03-rc0
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 256Mi
      cpu: 256m
    limits:
      memory: 256Mi
      cpu: 256m
