# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

{{- range $scenarioIdx,$scenarioName := $.Values.scenario }}
{{- $args := dict "scenarioName" $scenarioName "Values" $.Values }}
{{- range $officeIdx := until ( int ( include "smtc.noffices" $args ) ) }}
{{- $officeName := printf "%s-office%d" $scenarioName (add $officeIdx 1) }}
{{- if contains $.Values.buildScope $officeName }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $officeName }}-alert
  labels:
     app: {{ $officeName }}-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $officeName }}-alert
  template:
    metadata:
      labels:
        app: {{ $officeName }}-alert
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ $officeName }}-alert
          image: {{ $.Values.registryPrefix }}smtc_alert:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OFFICE
              {{- $args := dict "scenarioName" $scenarioName "Values" $.Values "officeIdx" $officeIdx }}
              value: {{ include "smtc.env.office" $args | quote }}
            - name: DBHOST
              {{- $args := dict "officeName" $officeName "Values" $.Values }}
              value: {{ include "smtc.env.dbhost" $args | quote }}
            - name: SERVICE_INTERVAL
              value: "3,5,15"
            - name: OCCUPENCY_ARGS
              value: "100000,8,3,1000,20"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
      {{ include "smtc.platform.node-selector" $ }}

{{- end }}

---
{{- end }}
{{- end }}
