# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Frinx s. r. o.

apiVersion: v2
name: frinx-machine
description: Kubernetes deployment of FRINX-machine
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 0.1.0
maintainers:
  - name: FRINX
dependencies:
  - condition: krakend.enabled
    name: krakend
    repository: https://FRINXio.github.io/helm-charts
    version: 1.0.1

  - condition: frinx-frontend.enabled
    name: frinx-frontend
    repository: https://FRINXio.github.io/helm-charts
    version: 1.0.0

  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x

  - condition: uniresource.enabled
    name: uniresource
    repository: https://FRINXio.github.io/helm-charts
    version: 1.0.1

  - condition: uniflow.enabled
    name: uniflow
    repository: https://FRINXio.github.io/helm-charts
    version: 1.1.0

  - condition: inventory.enabled
    name: inventory
    repository: https://FRINXio.github.io/helm-charts
    version: 2.0.0

  - condition: uniconfig-postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
    alias: uniconfig-postgresql

  - condition: uniconfig.enabled
    name: uniconfig
    repository: https://FRINXio.github.io/helm-charts
    version: 1.0.1

  - condition: demo-workflows.enabled
    name: demo-workflows
    repository: https://FRINXio.github.io/helm-charts
    version: 1.0.0
