# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 A5G Networks Inc.
# Default values for a5gblu-webui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    name: "a5g-blu-x86_64"
    # Overrides the image tag whose default is the chart Version.
    tag: "1.0.0"
    registryUrl: ""
    pullPolicy: IfNotPresent
  
  loadBalancerServiceIP: 
    webui: "192.168.11.241"

  peer:
    mongoServiceName: "a5gblu-mongo-1-0-0-service-mongo"
