// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message for a SayHello request
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message for a SayHello response
type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

// The request message for a JobTitle request
type TitleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TitleRequest) Reset()         { *m = TitleRequest{} }
func (m *TitleRequest) String() string { return proto.CompactTextString(m) }
func (*TitleRequest) ProtoMessage()    {}
func (*TitleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}
func (m *TitleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TitleRequest.Unmarshal(m, b)
}
func (m *TitleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TitleRequest.Marshal(b, m, deterministic)
}
func (dst *TitleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TitleRequest.Merge(dst, src)
}
func (m *TitleRequest) XXX_Size() int {
	return xxx_messageInfo_TitleRequest.Size(m)
}
func (m *TitleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TitleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TitleRequest proto.InternalMessageInfo

// The request message for a JobTitle response
type TitleResponse struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TitleResponse) Reset()         { *m = TitleResponse{} }
func (m *TitleResponse) String() string { return proto.CompactTextString(m) }
func (*TitleResponse) ProtoMessage()    {}
func (*TitleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}
func (m *TitleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TitleResponse.Unmarshal(m, b)
}
func (m *TitleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TitleResponse.Marshal(b, m, deterministic)
}
func (dst *TitleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TitleResponse.Merge(dst, src)
}
func (m *TitleResponse) XXX_Size() int {
	return xxx_messageInfo_TitleResponse.Size(m)
}
func (m *TitleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TitleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TitleResponse proto.InternalMessageInfo

func (m *TitleResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "example.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "example.HelloResponse")
	proto.RegisterType((*TitleRequest)(nil), "example.TitleRequest")
	proto.RegisterType((*TitleResponse)(nil), "example.TitleResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	JobTitle(ctx context.Context, in *TitleRequest, opts ...grpc.CallOption) (*TitleResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/example.Agent/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) JobTitle(ctx context.Context, in *TitleRequest, opts ...grpc.CallOption) (*TitleResponse, error) {
	out := new(TitleResponse)
	err := c.cc.Invoke(ctx, "/example.Agent/JobTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	JobTitle(context.Context, *TitleRequest) (*TitleResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Agent/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_JobTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).JobTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Agent/JobTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).JobTitle(ctx, req.(*TitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Agent_SayHello_Handler,
		},
		{
			MethodName: "JobTitle",
			Handler:    _Agent_JobTitle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49,
	0x55, 0x52, 0xe2, 0xe2, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0xb3, 0x95, 0xb4, 0xb9, 0x78, 0xa1, 0x6a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xa4, 0xb8,
	0x38, 0xd2, 0x8b, 0x52, 0x53, 0x4b, 0x32, 0xf3, 0xd2, 0xa1, 0x0a, 0xe1, 0x7c, 0x25, 0x3e, 0x2e,
	0x9e, 0x90, 0xcc, 0x92, 0x9c, 0x54, 0xa8, 0x81, 0x4a, 0xaa, 0x5c, 0xbc, 0x50, 0x3e, 0x54, 0xb3,
	0x08, 0x17, 0x6b, 0x09, 0x48, 0x00, 0xaa, 0x13, 0xc2, 0x31, 0x6a, 0x64, 0xe4, 0x62, 0x75, 0x04,
	0x39, 0x50, 0xc8, 0x9a, 0x8b, 0x23, 0x38, 0xb1, 0x12, 0x6c, 0xa1, 0x90, 0xa8, 0x1e, 0xd4, 0x9d,
	0x7a, 0xc8, 0x8e, 0x94, 0x12, 0x43, 0x17, 0x86, 0x18, 0xad, 0xc4, 0x00, 0xd2, 0xec, 0x95, 0x9f,
	0x04, 0xb6, 0x10, 0x49, 0x33, 0xb2, 0x83, 0x90, 0x34, 0xa3, 0xb8, 0x4b, 0x89, 0x21, 0x89, 0x0d,
	0x1c, 0x36, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0x79, 0x74, 0x08, 0x2a, 0x01, 0x00,
	0x00,
}
