# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.agent.configMap }}
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ .Values.component }}
data:
  otel-agent-config.yaml: |
    receivers:
      opencensus:
        endpoint: "{{ .Values.agent.receiver.opencensus.endpoint }}"

    exporters:
      opencensus:
        endpoint: "{{ .Values.agent.exporter.opencensus.endpoint }}"
        ca_file: {{ .Values.agent.rootca }}
        server_name_override: {{ .Values.agent.servername }}

    service:
      pipelines:
        metrics:
          receivers: [{{ .Values.agent.receivers }}]
          exporters: [{{ .Values.agent.exporters }}]
