# Copyright (c) 2020 ClearBlade, Inc. All rights reserved.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edge-config-claim2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
