#SPDX-License-Identifier: Apache-2.0
#Copyright (c) 2022 Kfx Circuits & Systems Private Limited

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kfxchart.serviceAccountName" . }}
  labels:
    {{- include "kfxchart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
