# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Inno Barn. All rights reserved.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configs" (include "curamedon-uploads.fullname" .) }}
data:
  APP_ENV: {{ .Values.app.configs.appEnv | quote }}
  TRUSTED_HOSTS: {{ .Values.app.configs.trustedHosts | quote }}
  TRUSTED_PROXIES: "127.0.0.1,REMOTE_ADDR"
  CORS_ALLOW_ORIGIN: {{ .Values.app.configs.corsAllowOrigin | quote }}
  INTERNAL_API_HOST: {{ .Values.app.configs.internalApiHost | quote }}
  JWT_SECRET_KEY: /srv/app/config/jwt/private.pem
  JWT_PUBLIC_KEY: /srv/app/config/jwt/public.pem
  JWT_TTL: {{ .Values.app.configs.jwtTtl | quote }}
  S3_DEFAULT_ENDPOINT: {{ .Values.app.configs.s3Endpoint | quote }}
  S3_DEFAULT_BUCKET: {{ .Values.app.configs.s3PrivateBucket | quote }}
  S3_DEFAULT_PUBLIC_BUCKET: {{ .Values.app.configs.s3PublicBucket | quote }}
  ENVIRONMENT_NAME: {{ .Values.app.configs.environmentName | quote }}
  TUS_STORAGE: {{ .Values.app.configs.storageClass | quote }}
  UPLOADS_STORAGE: {{ .Values.app.configs.storageClass | quote }}
  SCAN_FOR_VIRUSES: {{ .Values.app.configs.scanForViruses | quote }}
