# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Inno Barn. All rights reserved.

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "curamedon-uploads.fullname" .) }}
type: Opaque
data:
  APP_SECRET: {{ .Values.app.secrets.appSecret | b64enc | quote }}
  JWT_PASSPHRASE: {{ .Values.app.secrets.jwtPassphrase | b64enc | quote }}
  JWT_PUBLIC_KEY_CONTENT: {{ .Values.app.secrets.jwtPublicKeyContent | b64enc | quote }}
  JWT_PRIVATE_KEY_CONTENT: {{ .Values.app.secrets.jwtPrivateKeyContent | b64enc | quote }}
  INTERNAL_API_BASIC_AUTH: {{ .Values.app.secrets.internalApiBasicAuth | b64enc | quote }}
  TELEGRAM_LOG_API_KEY: {{ .Values.app.secrets.telegramLogApiKey | b64enc | quote }}
  TELEGRAM_LOG_CHANNEL: {{ .Values.app.secrets.telegramLogChannel | b64enc | quote }}
  S3_DEFAULT_ACCESS_KEY: {{ .Values.app.secrets.s3AccessKey | b64enc | quote }}
  S3_DEFAULT_SECRET_KEY: {{ .Values.app.secrets.s3SecretKey | b64enc | quote }}
  SENTRY_DSN: {{ .Values.app.secrets.sentryDsn | b64enc | quote }}
