# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Inno Barn. All rights reserved.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "curamedon-uploads.fullname" . }}
  labels:
    {{- include "curamedon-uploads.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "curamedon-uploads.selectorLabels" . | nindent 6 }}
  serviceName: {{ printf "%s-headless" (include "curamedon-uploads.fullname" .) }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "curamedon-uploads.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "curamedon-uploads.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "php"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ printf "%s-secrets" (include "curamedon-uploads.fullname" .) }}
            - configMapRef:
                name: {{ printf "%s-configs" (include "curamedon-uploads.fullname" .) }}
          volumeMounts:
            - name: uploads
              mountPath: /srv/app/uploads
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
        - name: "nginx"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 10
            failureThreshold: 5
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
        {{- if .Values.metrics.enabled }}
        - name: "metrics"
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PHP_FPM_SCRAPE_URI
              value: "tcp://localhost:9000/status"
        {{- end }}
        {{- if .Values.antivirus.enabled }}
        - name: "antivirus"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.antivirus.image.repository }}:{{ .Values.antivirus.image.tag }}"
          imagePullPolicy: {{ .Values.antivirus.image.pullPolicy }}
          volumeMounts:
            - name: uploads
              mountPath: /srv/app/uploads
            - name: antivirus_data
              mountPath: /data
          resources:
            {{- toYaml .Values.antivirus.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.antivirus.enabled }}
        - name: antivirus_data
          emptyDir: {}
        {{- end }}
  {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim . }}
  {{- else if not .Values.persistence.enabled }}
        - name: uploads
          emptyDir: {}
  {{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: uploads
        labels:
          {{- include "curamedon-uploads.labels" . | nindent 10 }}
      {{- if .Values.persistence.annotations }}
      annotations:
        {{- toYaml .Values.persistence.annotations | nindent 10 }}
      {{- end }}
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- if .Values.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.selector "context" $) | nindent 10 }}
        {{- end -}}
  {{- end }}
