# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Exium Inc.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.appName }}
    service: {{ .Values.name }}
  annotations:
    prometheus.io/scrape: {{ .Values.env.enableMetrics | quote }}
    prometheus.io/scheme: "http"
    prometheus.io/port: {{ .Values.env.metricsPort | quote }}
    prometheus.io/path: {{ .Values.env.metricsSuffix | quote }}
spec:
  selector:
    app: {{ .Values.appName }}
    name: {{ .Values.name }}
  type: {{ .Values.service.type }}
  #clusterIP: None
  ports:
   - name: grpc-n4fe
     port: 5056
     protocol: TCP
   - name: http 
     port: 8080
   
---
apiVersion: v1
kind: Service
metadata:
  name: upf-n4fe-pfcp
  labels:
    app: upf
    service: upf-n4fe
spec:
  externalTrafficPolicy: Local
  selector:
    app: upf
    name: upf-n4fe
  type: LoadBalancer
  ports:
   - name: pfcp
     protocol: UDP
     port: 8805
     targetPort: 8805

