# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Modaviti eMarketing Private Limited

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orbo-image-enhancement.serviceAccountName" . }}
  labels:
    {{- include "orbo-image-enhancement.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
