# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Modaviti eMarketing Private Limited

apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbo-image-enhancement.fullname" . }}
  labels:
    {{- include "orbo-image-enhancement.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "orbo-image-enhancement.selectorLabels" . | nindent 4 }}
