# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Actian Corporation

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "actianzen.fullname" . }}
  labels:
    {{- include "actianzen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "actianzen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "actianzen.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "actianzen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ZEN_ACCEPT_EULA
            value: "YES"
          - name: ZEN_PRODUCT
            value: "Enterprise"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /data
            name: zendata
          - mountPath: /logs
            name: zenlogs
      volumes:
      - name: zendata
        hostPath:
            path: {{ .Values.paths.data }}{{ include "actianzen.fullname" . }}
            type: DirectoryOrCreate
      - name: zenlogs
        hostPath:
            path: {{ .Values.paths.logs }}{{ include "actianzen.fullname" . }}
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
