# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2022 Intel Corporation
 
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: itm-all-ingress
  namespace: smartedge-apps
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
      - {}
  egress:
      - {}
