# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 A5G Networks Inc.
# Default values for a5gblu-mme.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

upf:
  subnet:
    - addr: 10.45.0.1/16
      apn: internet
  dns:
    - 8.8.8.8
    - 8.8.4.4

global:
  userplaneNode: "bit-wk2"

  image:
    name: "a5g-blu-x86_64"
    # Overrides the image tag whose default is the chart Version.
    tag: "1.0.0"
    registryUrl: ""
    pullPolicy: IfNotPresent
  
