replicaCount: 1

image:
  repository: vsblty.azurecr.io/vedge/ai-pipeline
  pullPolicy: Always
  tag: "1.1.18"

device:
  accessToken: ""

camera:
  rtsp: "" 

vcapp:
  dns: "localhost"
  port: 5051

imagePullSecrets: [name: regcred]
nameOverride: ""
fullnameOverride: ""

display:
  displayName: unix:0
  pythonVar: 1

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: true

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
